# Generated by Django 3.1.4 on 2022-06-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='Food',
        ),
    ]
